#Dockerfile
FROM ubuntu
LABEL maintainer="programmersafdar@live.com"
RUN apt-get update && apt-get install -y \
    curl \
    git \
    build-essential \
    python3 \
    python3-pip \
    python3-venv

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN apt-get update && apt-get install -y bash
RUN bash -c "source $HOME/.local/bin/env"
